// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SanAndreasMail.Persistence.Contexts;

namespace SanAndreasMail.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200829170303_CreateSanAndreasMailDB")]
    partial class CreateSanAndreasMailDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("SanAndreasMail.Domain.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("SanAndreasMail.Domain.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Destiny")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Origin")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTravelTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("SanAndreasMail.Domain.RouteSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Destiny")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Origin")
                        .HasColumnType("TEXT");

                    b.Property<int>("TravelTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RouteSections");
                });
#pragma warning restore 612, 618
        }
    }
}
